const data = [
    {
      id: 100,
      img: "https://www.butterfly.tt/flags/international.png",
      name: "International Online Store",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 1,
      img: "https://www.butterfly.tt/flags/albania.svg",
      name: "Albenia",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 2,
      img: "https://www.butterfly.tt/flags/austria.svg",
      name: "Austria",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 3,
      img: "https://www.butterfly.tt/flags/belarus.svg",
      name: "Belarus",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 4,
      img: "https://www.butterfly.tt/flags/belgium.svg",
      name: "Belgium",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 5,
      img: "https://www.butterfly.tt/flags/bosnia-and-herzegovina.svg",
      name: "Bosnia and Herzegovina",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 6,
      img: "https://www.butterfly.tt/flags/bulgaria.svg",
      name: "Bulgaria",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 7,
      img: "https://www.butterfly.tt/flags/australia.svg",
      name: "Australia",
      europe: false,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 8,
      img: "https://www.butterfly.tt/flags/brazil.svg",
      name: "Brazil",
      europe: false,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 9,
      img: "https://www.butterfly.tt/flags/canada.svg",
      name: "Canada",
      europe: false,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 10,
      img: "https://www.butterfly.tt/flags/china.svg",
      name: "China",
      europe: false,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 11,
      img: "https://www.butterfly.tt/flags/egypt.svg",
      name: "Egypt",
      europe: false,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 12,
      img: "https://www.butterfly.tt/flags/iran.svg",
      name: "Iran",
      europe: false,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 13,
      img: "https://www.butterfly.tt/flags/croatia.svg",
      name: "Croatia",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 14,
      img: "https://www.butterfly.tt/flags/cyprus.png",
      name: "Cyprus",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 15,
      img: "https://www.butterfly.tt/flags/czech-republic.svg",
      name: "Czech Republic",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 16,
      img: "https://www.butterfly.tt/flags/denmark.svg",
      name: "Denmark",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 17,
      img: "https://www.butterfly.tt/flags/estonia.svg",
      name: "Estonia",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 18,
      img: "https://www.butterfly.tt/flags/finland.svg",
      name: "Finland",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 19,
      img: "https://www.butterfly.tt/flags/france.svg",
      name: "France",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 20,
      img: "https://www.butterfly.tt/flags/germany.svg",
      name: "Germany",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 21,
      img: "https://www.butterfly.tt/flags/greece.svg",
      name: "Greece",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 22,
      img: "https://www.butterfly.tt/flags/hungary.svg",
      name: "Hungary",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 23,
      img: "https://www.butterfly.tt/flags/ireland.svg",
      name: "Ireland",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 24,
      img: "https://www.butterfly.tt/flags/italy.svg",
      name: "Italy",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 25,
      img: "https://www.butterfly.tt/flags/kosovo.svg",
      name: "Kosovo",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 26,
      img: "https://www.butterfly.tt/flags/latvia.svg",
      name: "Latvia",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 27,
      img: "https://www.butterfly.tt/flags/lithuania.svg",
      name: "Lithuania",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 28,
      img: "https://www.butterfly.tt/flags/luxembourg.svg",
      name: "Luxembourg",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 29,
      img: "https://www.butterfly.tt/flags/macedonia.png",
      name: "Macedonia",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    {
      id: 30,
      img: "https://www.butterfly.tt/flags/monaco.svg",
      name: "Monaco",
      europe: true,
      storeLink: "https://butterfly-adria.com/",
    },
    
  ]

export default data;
